# Usar Usuario, Clave y Base de Datos con su propia información, por ejemplo:
# POSTGRES_USER: gonzalezj       --->>> su apellido más la primera letra de su nombre
# POSTGRES_PASSWORD: Jesus556    --->>> una clave que ud. elija
# POSTGRES_DB: Prueba            --->>> la Base de Datos deberá tener el nombre de Prueba 

version: '3.8'
services:
  db:  
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: Prueba
      MYSQL_USER: lpescador
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"  # Cambiamos el puerto externo a 3307

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db  
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "1010:80"

